### ISSUE TITLE
Make Recurrence implement JsonObject

### ISSUE THREAD

**Issue by vishnuinfrrd** [nylas/nylas-java#5] opened 2020-07-09 11:59 UTC
Currently, Recurrence class doesn't implement JsonObject interface.

**Comment by ddlatham** [comment] 2020-07-09 15:45
@vishnuinfrrd 
It's true that Recurrence does not implement JsonObject.  How is that impacting you? Can you explain why you want it to, and how you are relying on JsonObject?  Currently, it seems to me that JsonObject is unnecessary and I am considering deprecating and removing it.

**Comment by vishnuinfrrd** [comment] 2020-07-09 16:25
@ddlatham I was getting below error when I tried accessing `messages().list()`

> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.nylas.Event$Recurrence and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.nylas.Message["events"]->java.util.ArrayList[0]->com.nylas.Event["recurrence"])

However, I could get rid of this error by setting `spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false` in _application.properties_ file.

**Comment by ddlatham** [comment] 2020-07-24 19:16
@vishnuinfrrd Apologies for not getting back to you sooner.  

That looks like an error trying to serialize a Message using the Jackson JSON library.  The Nylas Java SDK doesn't use jackson at all internally (rather, it uses Moshi for JSON serialization).  So I'd guess that something else in your application is trying to serialize the Message object using Jackson.  Does that sound right?  If not, can you share a more complete stack trace including the entry point into the the Nylas SDK code?

I did try to reproduce it or any other problem with listing Messages containing Events that have Recurrences and have not been able to reproduce any problem.

**Comment by vishnuinfrrd** [comment] 2020-07-27 04:07
Thanks @ddlatham for the updates.
Will check this and get back to you if we need any help.

**Comment by ddlatham** [comment] 2020-08-31 20:16
Closing.  Let us know if there is more needed here.

**Closed by ddlatham** 2020-08-31 20:16 UTC
