### ISSUE TITLE
Java SDK: Thread: thread.getMessages() return an empty list

### ISSUE THREAD

**Issue by warunaperera** [nylas/nylas-java#28] opened 2021-12-03 00:19 UTC
**Describe the bug**
The java SDK has a bug with thread.getMessages() method. Even if a thread has multiple messages, this method returns an empty array

**To Reproduce**

```
List<Message> messages = thread.getMessages();
```

**Expected behavior**
This method should return the message list

**SDK Version:**
1.9.0

**Additional context**
The doc samples or cases can not be achieved

**Comment by mrashed-dev** [comment] 2021-12-03 23:14
Thanks for reporting this, we'll investigate and provide a fix soon!

**Comment by mrashed-dev** [comment] 2021-12-06 22:17
@warunaperera I'm unable to replicate this issue. Are you getting the expanded view for threads? The API does not populated the `messages` key without explicitly fetching the threads in the expanded view. e.g.

```java
List<Thread> allThreads = account.threads().expanded(query).chunkSize(10).fetchAll();
```

The following snippet works for me:

```java
Instant end = ZonedDateTime.now().toInstant();
Instant start = end.minus(1, ChronoUnit.DAYS);
ThreadQuery query = new ThreadQuery()
		.limit(55)
		.lastMessageAfter(start)
		.lastMessageBefore(end)
		;
List<Thread> allThreads = account.threads().expanded(query).chunkSize(10).fetchAll();
System.out.println("result thread count: " + allThreads.size());
for (Thread thread : allThreads) {
	System.out.println(thread);
	List<Message> messages = thread.getMessages();
	for (Message email : messages) {
		System.out.println(email);
	}
}
```

If you're using the `expanded` view and it's still not working, please post your code snippet and any other relevant details that can help in reproducing this issue. Thank you!

**Comment by mrashed-dev** [comment] 2021-12-13 16:01
@warunaperera closing the ticket for now. Please try the above code snippet and if it doesn't work, please re-open this ticket with more detail and/or a code sample. Thank you!

**Closed by mrashed-dev** 2021-12-13 16:01 UTC
Labels: bug
